# Generated by Django 3.2.9 on 2021-11-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
