# Generated by Django 3.2.9 on 2021-11-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
