# Generated by Django 3.2.9 on 2021-11-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20211110_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='e_mail',
        ),
    ]
